server:
  port: 8071
  compression:
    enabled: true
    mime-types: text/javascript,application/javascript,text/css
spring:
  application:
    name: DroneHangar
  resources:
    static-locations: classpath:/static/

logging:
  level:
    root: WARN
    com.utrons: INFO
  path: /opt